export const EXCHANGE_LOADED = 'EXCHANGE_LOADED'

export const CANCELLED_ORDERS_LOADED = 'CANCELLED_ORDERS_LOADED'
export const FILLED_ORDERS_LOADED = 'FILLED_ORDERS_LOADED'
export const ALL_ORDERS_LOADED = 'ALL_ORDERS_LOADED'

export const ORDER_CANCELLING = 'ORDER_CANCELLING'
export const ORDER_CANCELLED = 'ORDER_CANCELLED'
export const ORDER_FILLING = 'ORDER_FILLING'
export const ORDER_FILLED = 'ORDER_FILLED'

export const EXCHANGE_ETHER_BALANCE_LOADED = 'EXCHANGE_ETHER_BALANCE_LOADED'
export const EXCHANGE_TOKEN_BALANCE_LOADED = 'EXCHANGE_TOKEN_BALANCE_LOADED'
export const BALANCES_LOADING = 'BALANCES_LOADING'
export const BALANCES_LOADED = 'BALANCES_LOADED'

export const TRANSFER_REQUEST = 'TRANSFER_REQUEST'
export const TRANSFER_SUCCESS = 'TRANSFER_SUCCESS'
export const TRANSFER_FAIL = 'TRANSFER_FAIL'
export const TRANSFER_RESET = 'TRANSFER_RESET'
